---
title: "Persistent colonization across SNP thresholds using concatenated reference genomes"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_MERLIN/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source functions
source("./lib/common_functions.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data
```{r} 
df_index <- readRDS("./data/dataset/MERLIN_cohort_index_cases_metadata_final.RDS") 
plasmid_data <- readRDS("./data/ESBL_plasmids/MERLIN_index_cohort_beta_lactam_location_data.RDS") %>% subset(genomic_id %in% df_index$genomic_id)
df_index <- left_join(df_index,plasmid_data)
```

# Replace variable
```{r}
clustering_data <- readRDS("./data/SNP_distances/deprecated/SNP_cluster_assignments/MERLIN_SNP_cluster_assignments_concatenated_references.RDS")
df_index <- left_join(df_index %>% select(-Species_ST_cluster),clustering_data %>% select(genomic_id,Species_ST_cluster_25) %>% rename("Species_ST_cluster"="Species_ST_cluster_25"))
```

# Households with index positive data (i.e., only can consider those) 
```{r}
ESCrE_index_positive_households <- df_index %>% subset(visit ==0 & WGS_escre==T) %>% .$household
```

# Taxonomical prolonged colonization   
```{r }
# Any ESCrE
any_prolonged <- lapply(ESCrE_index_positive_households,get_prolonged_colonization,df_index,variable='WGS_escre') %>% do.call(rbind,.) 

# Species
species_prolonged <- lapply(ESCrE_index_positive_households,get_prolonged_colonization,df_index,variable='Species') %>% do.call(rbind,.)

# Species + ST
species_ST_prolonged <- lapply(ESCrE_index_positive_households,get_prolonged_colonization,df_index,variable='Species_ST') %>% do.call(rbind,.)

# Species + ST + Cluster
species_ST_cluster_prolonged <- lapply(ESCrE_index_positive_households,get_prolonged_colonization,df_index,variable='Species_ST_cluster') %>% do.call(rbind,.)

# Add to master dataset
prolonged_df <- left_join(any_prolonged,species_prolonged) %>% left_join(.,species_ST_prolonged) %>% left_join(.,species_ST_cluster_prolonged)
```

# Genotype level prolonged colonization  
```{r} 
# MALDI classification from study laboratory
maldi_sharing <- lapply(ESCrE_index_positive_households,get_prolonged_colonization_genotype,df_index,variable='maldi',split=",") %>% do.call(rbind,.)

# ESCrE genes
ESCrE_genes_sharing <- lapply(ESCrE_index_positive_households,get_prolonged_colonization_genotype,df_index,variable='ESCrE_genes',split=";") %>% do.call(rbind,.)
 
# ESCrE plasmid aware
ESCrE_plasmid_aware_sharing <- lapply(ESCrE_index_positive_households,get_prolonged_colonization_plasmid_aware,df_index,chromosome_variable='ESCrE_chromosome_genes',plasmid_variable = "ESCrE_plasmid_genes",split=";",require_shared_plasmid=F,plasmid_cluster_variable=NULL,name='aware') %>% do.call(rbind,.)

ESCrE_plasmid_linked_sharing <- lapply(ESCrE_index_positive_households,get_prolonged_colonization_plasmid_aware,df_index,chromosome_variable='ESCrE_chromosome_genes',plasmid_variable = "ESCrE_plasmid_genes",split=";",require_shared_plasmid=T,plasmid_cluster_variable="plasmids",name='linked') %>% do.call(rbind,.)

ESCrE_plasmid_linked_specific_sharing <- lapply(ESCrE_index_positive_households,get_prolonged_colonization_plasmid_aware,df_index,chromosome_variable='ESCrE_chromosome_genes',plasmid_variable = "ESCrE_plasmid_genes",split=";",require_shared_plasmid=T,plasmid_cluster_variable="ESCrE_plasmids",name='shared') %>% do.call(rbind,.)

# Add to master dataset
prolonged_df <- left_join(prolonged_df,ESCrE_genes_sharing)  %>% left_join(.,ESCrE_plasmid_aware_sharing) %>% left_join(.,ESCrE_plasmid_linked_sharing) %>% left_join(.,ESCrE_plasmid_linked_specific_sharing) 
```

# Generate merged datapoints
```{r}
# Cluster + ESCrE genes
prolonged_df$index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes <- ifelse(prolonged_df$index_at_1_and_or_2_Species_ST_cluster==1 | prolonged_df$index_at_1_and_or_2_ESCrE_genes ==1,1,0) 

# Cluster + Plasmid-aware ESCrE genes
prolonged_df$index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes_plasmid_aware <- ifelse(prolonged_df$index_at_1_and_or_2_Species_ST_cluster==1 | prolonged_df$index_at_1_and_or_2_ESCrE_genes_plasmid_aware ==1,1,0) 

# Cluster + Plasmid-linked ESCrE  
prolonged_df$index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes_plasmid_linked <- ifelse(prolonged_df$index_at_1_and_or_2_Species_ST_cluster==1 | prolonged_df$index_at_1_and_or_2_ESCrE_genes_plasmid_linked ==1,1,0) 

# Cluster + Plasmid-linked ESCrE plasmids
prolonged_df$index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes_shared_ESCrE_plasmid  <- ifelse(prolonged_df$index_at_1_and_or_2_Species_ST_cluster==1 | prolonged_df$index_at_1_and_or_2_ESCrE_genes_plasmid_shared ==1,1,0) 
```

# Save dataset
```{r}
saveRDS(prolonged_df,'./data/persistent_colonization/deprecated/persistent_colonization_episodes/MERLIN_persistent_colonization_index_patients_concatenated_references.RDS')
```
