---
title: "Plasmid data curation via MOB-Suite"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

Notes:

1. This data is from short-read assemblies, so MOB-Suite data represent predictions of plasmid content

2. We used primary cluster ID data to use a big-picture representation of circulating plasmid lineages

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = T, message = T,error=T,comment=T) 
opts_chunk$set(echo = F,warning = T, message = T,error=T,comment=T)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_MERLIN/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=T, message=T, include=T, results=T}
#Packages
packages <- c("tidyverse") 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Functions
source("./scripts/mobsuite/mobsuite_functions.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load dataset

```{r cars} 
df <- readRDS("./data/dataset/MERLIN_cohort_metadata_final.RDS") %>% subset(WGS_escre == TRUE & qc_pass == TRUE) 
```

# Curate MOBSuite data

```{r}
# Mobtyper Results
mobtyper <- read_mobtyper_results(path = './data/mobsuite/MERLIN_mobtyper_results.txt', df = df) 
mobsuite_contigs <- read_mobtyper_results(path = './data/mobsuite/MERLIN_contig_report.txt', df = df)
mobsuite_contigs$location <- ifelse(mobsuite_contigs$primary_cluster_id=="-", "chromosome", mobsuite_contigs$primary_cluster_id)

# Save reports
saveRDS(mobtyper,file="./data/mobsuite/mobtyper.RDS")
saveRDS(mobsuite_contigs,file="./data/mobsuite/mobsuite_contigs.RDS")
```

# Create MOBSuite plasmid matrices
```{r}
# Convert Mobtyper data into a binary plasmid presence/absence matrix on the primary cluster and mash nearest neighbor level
## We will preferentially use the cluster matrix for downstream analyses
mash_nn_matrix <- get_mobtyper_mash_nn_matrix(df = df, mobtyper = mobtyper)  
cluster_matrix <- get_mobtyper_cluster_matrix(df = df, mobtyper = mobtyper) 

# Save matrices
saveRDS(mash_nn_matrix,file="./data/mobsuite/plasmid_mash_nn_matrix.RDS")
saveRDS(cluster_matrix,file="./data/mobsuite/plasmid_cluster_matrix.RDS") 
```