---
title: "Generate persistent colonization across strain and genotype data for concatenated references"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T, warning = T, message = T, error=T, comment=T) 
opts_chunk$set(echo = T, cdwarning = T, message = T, error=T, comment=T)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_MERLIN/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=T, message=T, include=T, results=T}
#Packages
packages <- c("tidyverse",'kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source function
source("./lib/common_functions.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data

```{r} 
df_index <- readRDS("./data/dataset/MERLIN_cohort_index_cases_metadata_final.RDS") 

clustering_data <- readRDS("./data/SNP_distances/deprecated/SNP_cluster_assignments/MERLIN_SNP_cluster_assignments_concatenated_references.RDS")
df_index <- left_join(df_index,clustering_data)
```

# Households with index positive data (i.e., only can consider those) 

```{r}
ESCrE_index_positive_households <- df_index %>% subset(visit ==0 & WGS_escre==T) %>% .$household

paste0("Number of households: ",length(ESCrE_index_positive_households))
```

# Prolonged colonization 

```{r}
prolonged_colonization_across_thresholds <- pbmcapply::pbmclapply(0:100, function(i) {
  lapply(ESCrE_index_positive_households, get_prolonged_colonization,
         df_index, variable = paste0('Species_ST_cluster_', i)) %>%
    do.call(rbind, .) %>% 
    mutate(threshold = i)  %>%
    rename_with(~ gsub(paste0('_Species_ST_cluster_', i), '', .x))
},mc.cores=10) %>%   do.call(rbind, .) 
```

# Save prolonged colonization data

```{r}
saveRDS(prolonged_colonization_across_thresholds,"./data/persistent_colonization/deprecated/threshold_sensitivity_strain_level/MERLIN_persistent_colonization_threshold_sensitivity_strain_level_concatenated_references.RDS")
write.csv(prolonged_colonization_across_thresholds,"./data/persistent_colonization/deprecated/threshold_sensitivity_strain_level/MERLIN_persistent_colonization_threshold_sensitivity_strain_level_concatenated_references.csv") 
```
