---
title: "Generate diagnostic statistics for species level using concatenated reference genome "
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_MERLIN/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source library
source("./lib/consistent_themes.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data

```{r } 
prolonged_colonization_df <- readRDS("./data/persistent_colonization/deprecated/persistent_colonization_episodes/MERLIN_persistent_colonization_index_patients_concatenated_references.RDS")
```

# Diagnostic statistics for species-level definition of prolonged colonization 
## Function to generate data
```{r}
get_marginal_stats <- function(feature,outcome){ 
  if(class(outcome) != "numeric"){
    stop("Outcome is not numeric")
  }
  if(class(feature) != "numeric"){
    stop("Feature is not numeric")
  }
  
  n <- length(outcome)
  phenotype_count = sum(outcome)
  phenotype_freq = phenotype_count / n
  feature_count = sum(feature)
  feature_freq = feature_count / n
  
  # Cells
  tp = sum(outcome==1 & feature==1)
  fp = sum(outcome==0 & feature==1)
  tn = sum(outcome==0 & feature==0)
  fn = sum(outcome==1 & feature==0)
  # Summary stats
  sens = round((tp / c(tp + fn)),3) *100
  spec = round((tn / c(tn + fp)),3) *100
  ppv = round((tp / c(tp + fp)),3) *100
  npv = round((tn / c(tn + fn)),3) *100
  accuracy =  round(((tp+tn)/n),3) *100
  precision_raw = tp  / (tp+fp)
  recall_raw = tp / (tp + fn)
  f1 = round(2*precision_raw*recall_raw / (precision_raw + recall_raw),3)  *100
  recall = round(recall_raw,3) *100
  precision = round(precision_raw,3) *100
  lr_pos = round(sens / (100-spec),2)
  false_persistence_rate = round(100-ppv,2)
  overall_disagreement = round(100-accuracy,2)
  
  # Data
  data <- as.data.frame(cbind(phenotype = colnames(outcome),phenotype_count,phenotype_freq,feature_count,feature_freq,tp,fp,fn,tn,sens,spec,ppv,npv,recall,precision,f1,accuracy,lr_pos,false_persistence_rate,overall_disagreement))
  # Add rownames
  rownames(data) <- colnames(feature)
  # Create name variable
  data$name <-colnames(feature)
  return(data)
}
```

# Generate data

```{r,fig.height=9.75,fig.width=7.8}
# Outcomes of interest (to compare to species level data)
outcomes <- c('index_at_1_and_or_2_Species_ST','index_at_1_and_or_2_Species_ST_cluster',"index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes_plasmid_linked")

# Compare marginal statistics
comparison_of_any_ESCRE_to_WGS_outcomes <- lapply(outcomes,FUN=function(x){
  get_marginal_stats(prolonged_colonization_df$index_at_1_and_or_2_Species,prolonged_colonization_df[[x]])
}) %>% do.call(rbind,.) %>% mutate(outcome = outcomes) 

# Rename the outcome to a more informative data
comparison_of_any_ESCRE_to_WGS_outcomes$outcome_rename <- recode(comparison_of_any_ESCRE_to_WGS_outcomes$outcome,
                                                                 'index_at_1_and_or_2_WGS_escre'='Any ESCrE',
                                                                 'index_at_1_and_or_2_Species'='Species',
                                                                 'index_at_1_and_or_2_Species_ST'='Same sequence type',
                                                                 'index_at_1_and_or_2_Species_ST_cluster'='Same strain',
                                                                 'index_at_1_and_or_2_ESCrE_genes'='ESCrE gene',
                                                                 'index_at_1_and_or_2_ESCrE_plasmidic_genes'= 'Plasmidic ESCrE gene',
                                                                 'index_at_1_and_or_2_ESCrE_plasmids'= 'ESCrE plasmid',
                                                                 'index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes'='Strain + ESCrE gene',
                                                                 'index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes_plasmid_linked'='Same strain + plasmid-linked ESCrE gene') %>% factor(.,levels = c("Same sequence type", "Same strain", "Same strain + plasmid-linked ESCrE gene"))

# Show data
comparison_of_any_ESCRE_to_WGS_outcomes %>% favorite_kable()
```

# Save the data

```{r}
saveRDS(comparison_of_any_ESCRE_to_WGS_outcomes,"./data/diagnostic_statistics/deprecated//species_level_persistence_diagnostic_statistics/species_level_diagnostic_statistics_concatenated_references.RDS")
write.csv(comparison_of_any_ESCRE_to_WGS_outcomes,"./data/diagnostic_statistics/deprecated/species_level_persistence_diagnostic_statistics/species_level_diagnostic_statistics_concatenated_references.csv")
```
