---
title: "MERLIN_SNP_Pair_DF"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_merlin/')
```
# Environment

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse",'ape','kableExtra','phytools','igraph','ggraph','tableone','kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

```{r} 
df <- readRDS("./Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/data/dataset/metadata_w_genomic_id_w_duplicate_ESCrE_addressed_w_qcd.RDS") %>% subset(escre==T & qc_pass==T)
``` 

```{r}
species <- table(df$Species) %>% subset(.>1)  %>% names
species_simple <- str_split(string = species,pattern = " ",simplify = T) %>% apply(.,1,FUN=function(x){
  genus <- x[1] %>% substr(.,1,1)  %>% tolower()
  species <- x[2]
  paste0(genus,species)}) 

dist_matrices <- readRDS('./Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/data/SNP_distance/MERLIN_SNP_distance_matrices.RDS')
```

```{r}
# Subset metadata to species
clean_datasets <- function(metadata,mat,species){
  # Curate datasets
  species_df <- metadata %>% subset(Species ==species)  
  rownames(species_df) <- species_df$isolate_no
  species_mat <- mat[species_df$genomic_id,species_df$genomic_id]
  # Update datasets
  results <- list(species_df,species_mat) %>% `names<-`(c("df","mat"))
  return(results)
}

for(i in species){
  species_abrev <- str_split(string = i,pattern = " ",simplify = T) %>% apply(.,1,FUN=function(x){
  genus <- x[1] %>% substr(.,1,1)  %>% tolower()
  species <- x[2]
  paste0(genus,species)}) 
  assign(paste0(species_abrev,"_data"),
       clean_datasets(df,dist_matrices[[species_abrev]],species = i))
} 
```

# Get pairwise distances
```{r}
get_cell_info <- function(mat) {
  idx <- which(!is.na(mat) & lower.tri(mat) , arr.ind = TRUE)
  data.frame(
    isolate1 = rownames(mat)[idx[, 1]],
    isolate2 = colnames(mat)[idx[, 2]],
    pairwise_dist = mat[idx]
  )
}
```

```{r}
get_pair_types_mat <- function(dataset,mat,type,voi){ 
  pair_types <- get_cell_info(mat = mat)
  pair_types_info <-  update_pair_types_w_info(pair_types,df=dataset,voi=voi) 
  pair_types_df <- left_join(pair_types,pair_types_info)  
  pair_types_df$pairwise_dist <- as.numeric(pair_types_df$pairwise_dist)
  return(pair_types_df) 
}

update_pair_types_w_info <- function(pair_types_df,df,voi){ 
  df_subset <- df[, c("genomic_id", voi), drop = FALSE]

  # Join on isolate1
  pair_types_df <- pair_types_df %>%
    dplyr::left_join(df_subset, by = c("isolate1" = "genomic_id")) %>%
    dplyr::rename_with(~ paste0(., "1"), .cols = voi)

  # Join on isolate2
  pair_types_df <- pair_types_df %>%
    dplyr::left_join(df_subset, by = c("isolate2" = "genomic_id")) %>%
    dplyr::rename_with(~ paste0(., "2"), .cols = voi)
  
  return(as.data.frame(pair_types_df))
} 
```


 
```{r}
voi = c("household","Species","Species_ST","specimen",'visit','specimen_category','individual_id')

pairtype_datasets <- pbmcapply::pbmclapply(species_simple,FUN=function(x){ 
  data <- get(paste0(x,"_data"))
  get_pair_types_mat(data$df,data$mat,type="hospital_location",voi=voi)   
},mc.cores=6) %>% `names<-`(species_simple)

# Overall
overall_pair_types <- do.call(rbind,pairtype_datasets) 
```

```{r} 
saveRDS(overall_pair_types,'./Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/data/SNP_distance/MERLIN_SNP_distance_pairs_dataset.RDS') 
```
