---
title: "Figure 1: Prolonged colonization across molecular definitions"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_merlin/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source library
source("./lib/consistent_themes.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Data
```{r } 
prolonged_colonization_df <- readRDS("./data/prolonged_colonization/MERLIN_prolonged_colonization_index_patients.RDS")
```

# Generate frequency plot
```{r}
prolonged_melt <- reshape2::melt(prolonged_colonization_df %>% select(household,index_at_1_and_or_2_WGS_escre,index_at_1_and_or_2_Species,index_at_1_and_or_2_Species_ST,index_at_1_and_or_2_Species_ST_cluster,index_at_1_and_or_2_ESCrE_genes,index_at_1_and_or_2_ESCrE_plasmidic_genes,index_at_1_and_or_2_ESCrE_plasmids,index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes,index_at_1_and_or_2_Species_ST_cluster_ESCrE_plasmidic_genes,index_at_1_and_or_2_Species_ST_cluster_ESCrE_plasmids),id.vars="household")
prolonged_melt$value <- factor(prolonged_melt$value,levels = c(0,1))
prolonged_melt$variable <- recode(prolonged_melt$variable,'index_at_1_and_or_2_WGS_escre'='Any ESCrE','index_at_1_and_or_2_Species'='Species','index_at_1_and_or_2_Species_ST'='Sequence type','index_at_1_and_or_2_Species_ST_cluster'='Strain','index_at_1_and_or_2_ESCrE_genes'='ESCrE gene','index_at_1_and_or_2_ESCrE_plasmidic_genes'= 'Plasmidic ESCrE gene','index_at_1_and_or_2_ESCrE_plasmids'= 'ESCrE plasmid',
  'index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes'='Strain +/- ESCrE gene',
  'index_at_1_and_or_2_Species_ST_cluster_ESCrE_plasmidic_genes'='Strain +/- plasmidic ESCrE gene',
  'index_at_1_and_or_2_Species_ST_cluster_ESCrE_plasmids'='Strain +/- ESCrE plasmid')

prolonged_melt %>% mutate(value = (value ==1)) %>% group_by(variable) %>% summarise(n=sum(value),prop=n/length(value)) %>% favorite_kable()
```

```{r,fig.width=6.5,fig.height=8.125}
summary_data <- prolonged_melt%>% mutate(value = (value ==1)) %>% group_by(variable) %>% summarise(n=sum(value),prop=n/length(value))  

figure_2 <- ggplot(data=prolonged_melt) + geom_bar(aes(x=variable,fill=value)) + xlab("") + ylab("Count") +  geom_text(data=summary_data,aes(x=variable,y = n,label=n), vjust=0,nudge_y=0.5,color ='black',size = 5)  + prolonged_colonization_scale + theme_bw_me + figure_2_format 

figure_2
```

```{r}
ggsave(plot = figure_2,filename = './figures/figure_1_prolonged_colonization.png', dpi = 900, width = 6.5, height = 8.125,bg='white')
```