---
title: "Supplementary Figure 1: Pairwise distance comparisons by participant"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_MERLIN/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```
 
# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'ggplot2','gridExtra','cowplot') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Scripts
source("./lib/consistent_themes.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
``` 

# Load data
```{r}
df_index <- readRDS("./data/dataset/MERLIN_cohort_index_cases_metadata_final.RDS")
overall_pair_types <- readRDS("./data/SNP_distances/SNP_pairwise_datasets/MERLIN_SNP_pairwise_datasets_public_references.RDS") 
```

# Update pairtypes with the following questions
```{r}
update_pair_types_df_w_questions <- function(pair_types_df){
  both_index_cases <- ifelse(pair_types_df$index1==T & pair_types_df$index2==T,T,F)
  index_isolates <- ifelse(pair_types_df$visit1==0 & pair_types_df$visit2==0,T,F)
  same_household <- ifelse(pair_types_df$household1==pair_types_df$household2,T,F)
  same_household_visit <- ifelse(pair_types_df$household1==pair_types_df$household2 & pair_types_df$visit1==pair_types_df$visit2,T,F) 
  same_individual <- ifelse(pair_types_df$ncbi_id1==pair_types_df$ncbi_id2,T,F)
  ST_pair <- ifelse(pair_types_df$Species_ST1==pair_types_df$Species_ST2,T,F)
  same_specimen_category <- ifelse(pair_types_df$subject_type1 ==pair_types_df$subject_type2,T,F)
  both_human <- ifelse(pair_types_df$subject_type1 == "Human" & pair_types_df$subject_type2 == "Human",T,F)
  both_pet <- ifelse(pair_types_df$subject_type1 == "Pet" & pair_types_df$subject_type2 == "Pet",T,F)
  both_env <- ifelse(pair_types_df$subject_type1 == "Environment" & pair_types_df$subject_type2 == "Environment",T,F)  
  
  dataset <- cbind(pair_types_df,both_index_cases=both_index_cases,index_isolates=index_isolates,same_household=same_household,same_household_visit=same_household_visit,ST_pair=ST_pair,same_specimen_category=same_specimen_category,same_individual=same_individual,both_human=both_human,both_pet=both_pet,both_env=both_env)
  return(dataset)
}
```

# Annotate and subset database
```{r,fig.width=8,fig.height=5}
# Annotate
overall_pair_types <- overall_pair_types %>% update_pair_types_df_w_questions 

# Subset to index isolates
overall_pair_types_index <- subset(overall_pair_types,ncbi_id1 %in%  df_index$ncbi_id & ncbi_id2 %in% df_index$ncbi_id)
```

# A. Overall  
```{r,fig.width=8,fig.height=4}
overall_pair_types_index <- as.data.frame(overall_pair_types_index)
overall_pair_types_index$pairwise_dist <- as.numeric(overall_pair_types_index$gubbins_masked_noncore)

# Get max x value
x_max   <- max(overall_pair_types_index$pairwise_dist, na.rm = TRUE)
x_limit <- ceiling(x_max / 20000) * 20000  

# Get max y value
build_data <- ggplot_build(
  ggplot(overall_pair_types_index, aes(x = pairwise_dist, fill = same_household)) +
    geom_histogram(bins = 100)
)$data[[1]]

y_max <- max(tapply(build_data$count, build_data$x, sum))
y_breaks <-  scales::pretty_breaks(6)(c(0, y_max * 1.05))

# Overall figure
s_figure_1 <- ggplot(data=overall_pair_types_index,aes(x=pairwise_dist,fill=same_household)) + geom_histogram(bins=100) + xlab("Pairwise SNP distance") + ylab("Number of pairs") + theme_bw_me + pairtype_fill  + s_figure_1_format + scale_y_continuous(breaks =  y_breaks) + scale_x_continuous(
    breaks = seq(0, x_limit, by = 20000)
  ) + coord_cartesian(xlim = c(NA, x_limit + 10), ylim = c(NA, max(y_breaks)*1.0025))
s_figure_1

# Insert of 0 to 200
## xmax
x_max_sub   <- max(overall_pair_types_index %>% subset(pairwise_dist <=200) %>% .$pairwise_dist, na.rm = TRUE)
x_limit_sub <- ceiling(x_max_sub / 25) * 25  
x_breaks_sub <- sort(c(25, seq(0, x_limit_sub, by = 50)))

## ymax 
build_data_sub <-  ggplot_build(
  ggplot(overall_pair_types_index %>% subset(pairwise_dist <= 200),
         aes(x = pairwise_dist, fill = same_household)) +
    geom_histogram(binwidth = 1)  # match the actual inset
)$data[[1]]

y_max_sub    <- max(tapply(build_data_sub$count, build_data_sub$x, sum))
y_breaks_sub <- scales::pretty_breaks(5)(c(0, y_max_sub ))
y_limit_sub  <- max(y_breaks_sub)
 
## Figure
s_figure_1_inlet <- ggplot(data=overall_pair_types_index %>% subset(pairwise_dist <=200), aes(x=pairwise_dist,fill=same_household)) + geom_vline(xintercept = 18,colour = 'red',linetype = 2,alpha=0.5) +  geom_histogram(binwidth = 1) + theme_bw_me + xlab("") + ylab("") + pairtype_fill  + s_figure_1_inset_format  +
  scale_x_continuous(breaks = x_breaks_sub) +
  scale_y_continuous(breaks = y_breaks_sub) +
  coord_cartesian(xlim = c(NA, x_limit_sub + 10), ylim = c(NA, y_limit_sub))

s_figure_1_inlet

s_figure_1A <- s_figure_1 +  annotation_custom(ggplotGrob(s_figure_1_inlet), xmin = 61000, xmax = x_limit*1.0175, ymin = 100, ymax = max(y_breaks)*1.09)

s_figure_1A
```

# B - Species and Major ST data
```{r,fig.width=8,fig.height=6} 
overall_pair_types_index$group1 <- ifelse(overall_pair_types_index$Species1 != 'Escherichia coli',
                                          overall_pair_types_index$Species1,
                                          ifelse(overall_pair_types_index$Species1 == "Escherichia coli" & overall_pair_types_index$Species_ST1 == "Escherichia coli ST 131","Escherichia coli ST 131","Escherichia coli Non-ST 131"))
overall_pair_types_index$group2 <- ifelse(overall_pair_types_index$Species2 != 'Escherichia coli',
                                          overall_pair_types_index$Species2,
                                          ifelse(overall_pair_types_index$Species2 == "Escherichia coli" & overall_pair_types_index$Species_ST2 == "Escherichia coli ST 131","Escherichia coli ST 131","Escherichia coli Non-ST 131"))

groups <- sort(unique(overall_pair_types_index$group1))
 
s_figure_1B <- lapply(groups,FUN=function(x){
  pair_types_subset <- overall_pair_types_index %>% subset(group1 == x & group2 == x)
  pair_types_subset$pairwise_dist <- as.numeric(pair_types_subset$pairwise_dist)
  max_val <- pair_types_subset$pairwise_dist %>% max  
  unique_values <- pair_types_subset$pairwise_dist %>% unique %>% length
  value_under_200 <- sum(pair_types_subset$pairwise_dist <= 200) >0
  
  # Title plot
  title <- ggdraw() + 
  draw_label(label = x,
    fontface = 'bold.italic',
    x = 0.1, 
    hjust = 0,
    vjust = 0.75,
    size = 12,
    
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
  
# Overall figure
s_figure_1 <- ggplot(data=pair_types_subset,aes(x=pairwise_dist,fill=same_household)) + geom_histogram(bins= 100) + xlab("Pairwise SNP distance") + ylab("Number of pairs") + theme_bw_me + pairtype_fill  + s_figure_1_species_format   + theme(legend.position='none')  + scale_y_continuous(breaks = function(x) { 
      b <- scales::extended_breaks()(x)
      b[b %% 1 == 0]  
    })
  if(unique_values == 1) {
    s_figure_1 <- s_figure_1 + scale_x_continuous(breaks = max_val,limits = c(max_val-.01,max_val+.01)) + scale_y_continuous(breaks = c(0,1))
  } 
  if(x %in% c("Enterobacter hormaechei","Klebsiella pneumoniae")){
    s_figure_1 <- s_figure_1 + scale_x_continuous(breaks = scales::pretty_breaks(3))
  } 
  if(x %in% c("Enterobacter hormaechei","Klebsiella pneumoniae")){
    s_figure_1 <- s_figure_1 + scale_x_continuous(breaks = scales::pretty_breaks(3))
  } 

if(max_val > 200 & value_under_200 == T){
  pair_types_under_200 <- pair_types_subset %>% subset(pairwise_dist <=200)
  max_pt_u_500 <- pair_types_under_200
  xmax <- max(pair_types_under_200$pairwise_dist) 
  
  bins_val <- n_distinct(pair_types_under_200$pairwise_dist)
  
s_figure_1_inlet <- ggplot(data=pair_types_under_200,aes(x=pairwise_dist,fill=same_household)) + geom_vline(xintercept = 18,colour = 'red',linetype = 2,alpha=0.5) + geom_histogram(binwidth = 1) + theme_bw_me + xlab("Pairwise SNP distance") + ylab("") + pairtype_fill  + s_figure_1_species_format  + theme(legend.position='none')  + scale_y_continuous(breaks = function(x) { 
      b <- scales::extended_breaks()(x)
      b[b %% 1 == 0]  
    })
s_figure_1 <- cowplot::plot_grid(s_figure_1 + theme(plot.margin = margin(t = 0, r = 8, b = 0, l = 5, "pt")),s_figure_1_inlet+ theme(plot.margin = margin(t = 0, r = 8, b = 0, l = 0, "pt"))) 

} else {
  s_figure_1 <- cowplot::plot_grid(s_figure_1 + theme(plot.margin = margin(t = 0, r = 8, b = 0, l = 5, "pt")),NULL,ncol=2)
} 


s_figure_1_final <- plot_grid(
  title, s_figure_1,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.15, 1)
)
s_figure_1_final

}) %>% cowplot::plot_grid(plotlist = .,labels = NULL,ncol=2,label_size = 12,hjust = -1.25)
```

# Full figure

```{r,fig.width=8,fig.height=10} 
s_figure_1_full <- cowplot::plot_grid(s_figure_1A, s_figure_1B,
                                      ncol=1, rel_heights = c(.6,1),
                                      labels = c("A","B"),
                                      label_size = 16,vjust = 1.5) 

s_figure_1_full
```

# Save figure

```{r}
ggsave(plot = s_figure_1_full,filename = './figures/s_figure_1_pairwise_SNP_distance.png', dpi = 900, width = 8, height = 10, bg='white')
```