---
title: "Supplemental Figure 2: MobSuite plasmid clusters"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_merlin/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'kableExtra','ComplexHeatmap') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data
```{r cars} 
df_index <- readRDS("./data/dataset/MERLIN_cohort_index_cases_metadata_final.RDS") 
plasmid_data <- readRDS("./data/ESBL_plasmids/MERLIN_index_cohort_beta_lactam_location_data.RDS") %>% subset(genomic_id %in% df_index$genomic_id)

df_index <- left_join(df_index,plasmid_data)
```

# Mobsuite data
```{r}
mobtyper <- readRDS("./data/mobsuite/mobtyper.RDS") %>% subset(genomic_id %in% df_index$genomic_id)
mobsuite_contigs <- readRDS("./data/mobsuite/mobsuite_contigs.RDS")  %>% subset(genomic_id %in% df_index$genomic_id)
ESCrE_plasmidic <- readRDS("./data/ESBL_plasmids/MERLIN_index_cohort_ESCrE_proportion_plasmidic.RDS")
ESCrE_gene_data_info <- readRDS("./data/amrfinder/beta_lactamase_summary_MERLIN_cohort.RDS")
amrfinder <- readRDS("./data/amrfinder/amrfinder_cleaned.RDS") %>% subset(genomic_id %in% df_index$genomic_id)
amrfinder_escre <- subset(amrfinder,element_symbol_renamed %in% c(ESCrE_gene_data_info %>% subset(ESCrE==T) %>% .$element_symbol_renamed))
```


## GET ESCrE gene data
```{r}
# Contig data
amrfinder_escre_info <- amrfinder_escre %>% select(genomic_id,contig_id,element_symbol_renamed) %>% group_by(genomic_id,contig_id) %>% summarise(ESCrE_gene = paste0(sort(element_symbol_renamed),collapse = " & ")) 

mobsuite_contigs <- left_join(mobsuite_contigs,amrfinder_escre_info)
mobsuite_contigs$ESCrE_gene_present <- !is.na(mobsuite_contigs$ESCrE_gene)

# Mobtyper data 
chromosome_plasmid_escre_data <- mobsuite_contigs %>% select(genomic_id,primary_cluster_id,ESCrE_gene,ESCrE_gene_present) %>% group_by(genomic_id,primary_cluster_id) %>% summarise(ESCrE_gene = paste0(sort(ESCrE_gene),collapse = " & ")) %>% mutate(ESCrE_gene_present =  ESCrE_gene != '')

mobtyper <- left_join(mobtyper,chromosome_plasmid_escre_data)


# Levels
plasmid_levels <-  names(mobtyper$primary_cluster_id  %>% table %>% sort(decreasing = T)) 
mobtyper$primary_cluster_id <- factor(mobtyper$primary_cluster_id,levels = plasmid_levels)
mobsuite_contigs$primary_cluster_id <- factor(mobsuite_contigs$primary_cluster_id,levels = c(plasmid_levels,'-'))
```


# A. Overall data
```{r} 
plasmid_scale <-  scale_fill_manual(breaks = c(1,0),values=c("red","gray"),labels = c("Present","Absent"),name = "ESCrE gene",guide = guide_legend(nrow=2, title.position = "top", label.position = "right"))
KPC_contig_bool <-  scale_fill_manual(breaks = c(T,F),values=c("red","gray"),labels = c("Present","Absent"),name = "ESCrE gene",guide = guide_legend(nrow=2, title.position = "top", label.position = "right"))
 

ESCrE_plasmids <- mobsuite_contigs %>% subset(molecule_type !='chromosome' & ESCrE_gene_present==T) %>% .$primary_cluster_id %>% unique  

A <- ggplot(data=mobtyper %>% subset(primary_cluster_id %in% ESCrE_plasmids) %>% distinct,aes(x=primary_cluster_id,fill=ESCrE_gene_present)) + geom_bar(stat='count')  + KPC_contig_bool  + 
    theme_bw_me + theme(axis.text.x = element_text(angle=45,hjust=1)) + 
    labs(x="Primary MOB-cluster",y="Isolates",fill="blaKPC-containing plasmid")  + scale_y_continuous(breaks = scales::breaks_pretty(9))
A
```


# B - Gene data 
```{r}  
genotypes <- unique(sort(mobtyper$ESCrE_gene %>% subset(.!='')))
genotypes_html <- sapply(genotypes, FUN = function(x) {
  paste0("<i>bla</i><sub>", gsub("bla", "", x), "</sub>")
})

genotype_scale <- scale_fill_manual(values = hues::iwanthue(length(genotypes)),breaks = genotypes,labels = genotypes_html, name = "ESCrE gene", guide = guide_legend(nrow=2, title.position = "top", label.position = "right"))
                                    
 
B <- ggplot(data=mobtyper %>% subset(primary_cluster_id %in% ESCrE_plasmids & ESCrE_gene_present==T),aes(x=primary_cluster_id,fill=ESCrE_gene)) + geom_bar(stat='count')  + 
  theme_bw_me + theme(axis.text.x = element_text(angle=45,hjust=1)) +  labs(x="Primary MOB-cluster",y="Isolates",fill="ESCrE gene") + genotype_scale+ scale_y_continuous(breaks = scales::breaks_pretty(6)) + theme(legend.text = ggtext::element_markdown())
B
```

# C. Contig count
```{r}
C <-  ggplot(data=mobtyper %>% subset(primary_cluster_id %in% ESCrE_plasmids),aes(x=primary_cluster_id,y=num_contigs,fill=ESCrE_gene_present)) + geom_boxplot(aes(y=num_contigs))  + 
  theme_bw_me + theme(axis.text.x = element_text(angle=45,hjust=1)) + 
  labs(x="",y="Number of contigs",fill="ESCrE plasmid")  + KPC_contig_bool  + scale_y_continuous(breaks = scales::breaks_pretty(5))

C
```

# D. Size
```{r}
D <-  ggplot(data=mobtyper %>% subset(primary_cluster_id %in% ESCrE_plasmids),aes(x=primary_cluster_id,y=size,fill=ESCrE_gene_present)) + geom_boxplot()   + 
  theme_bw_me + theme(axis.text.x = element_text(angle=45,hjust=1)) + 
  labs(x="",y="Size of plasmid (bp)",fill="ESCrE plasmid")   + scale_y_continuous(breaks = scales::breaks_pretty(5)) + KPC_contig_bool

D
```

# E. KPC contig size 
```{r} 
KPC_contig_data <- mobsuite_contigs %>% subset(primary_cluster_id != "-" & primary_cluster_id %in% ESCrE_plasmids) 
E <-  ggplot(data=KPC_contig_data  ,aes(x=primary_cluster_id,y=size,fill=ESCrE_gene_present)) + geom_boxplot()  + KPC_contig_bool + 
  theme_bw_me + theme(axis.text.x = element_text(angle=45,hjust=1)) + 
  labs(x="",y="Contig size (bp)",fill="carbapenemase-containing contig")     + scale_y_continuous(breaks = scales::breaks_pretty(5))

E
```

# F. Predicted Mobility
```{r}
mobility_scale <- scale_fill_manual(values = c("brown","blue","#C0C0C0"),breaks = c("conjugative",'mobilizable','non-mobilizable'),labels = c("Conjugative","Mobilizable","Non-Mobilizable"),name="Predicted mobility",guide = guide_legend(nrow=1, title.position = "top", label.position = "right"))

## Predicted mobility 
mobtyper$plasmid_name <- ifelse(mobtyper$ESCrE_gene_present ==T,"ESCrE plasmid","Non-ESCrE plasmid")
f <- ggplot(data=mobtyper%>% subset(primary_cluster_id %in% ESCrE_plasmids),aes(x=primary_cluster_id,fill=predicted_mobility))  + geom_bar()+ facet_wrap(~plasmid_name)  +   labs(x="",y="Isolates",fill="Predicted mobility") + theme_bw_me + 
  theme_bw_me + theme(axis.text.x = element_text(angle=45,hjust=1),
                      strip.background = element_rect(color = 'black',linewidth = 1)) + mobility_scale + scale_y_continuous(breaks = scales::breaks_pretty(5))
  
f
```

# G. Observed host range

```{r}
color_range <- hues::iwanthue(n = 6,hmin = 0,hmax = 75,plot = T)

host_range_scale <- scale_fill_manual(values = c("darkgray", color_range ),breaks = c("Actinomycetota,Bacillota,Pseudomonadota","Klebsiella","Enterobacteriaceae","Enterobacterales"                            ,"Gammaproteobacteria","Salmonella"),labels =  c("Actinomycetota, Bacillota, Pseudomonadota","Klebsiella","Enterobacteriaceae","Enterobacterales"                            ,"Gammaproteobacteria","Salmonella"),name="Observed host range",guide = guide_legend(nrow=1, title.position = "top", label.position = "right"))

G <-    ggplot(data=mobtyper%>% subset(primary_cluster_id %in% ESCrE_plasmids),aes(x=primary_cluster_id,fill=observed_host_range_ncbi_name))  + geom_bar()+ facet_wrap(~plasmid_name)    +  labs(x="",y="Isolates",fill="Observed host range")+ theme_bw_me + 
  theme_bw_me + theme(axis.text.x = element_text(angle=45,hjust=1),
                      strip.background = element_rect(color = 'black',linewidth = 1)) + host_range_scale  + scale_y_continuous(breaks = scales::breaks_pretty(5))

G
```

# H. Replicon type
```{r}  
rep_type_matrix <- mobtyper %>% subset(primary_cluster_id %in% ESCrE_plasmids) %>% select(genomic_id,primary_cluster_id,rep_types)%>%
  separate_rows(rep_types,sep=",") %>%
  group_by(primary_cluster_id,rep_types) %>%
  summarise(n=n(),.groups='drop') %>% as.data.frame %>% mutate(rep_types = recode(rep_types,"-" = 'Absent')) %>% 
  pivot_wider(names_from = rep_types,values_from = n,values_fill = 0) %>%
  as.data.frame() %>% `rownames<-`(.$primary_cluster_id) %>% select(-primary_cluster_id)  

H <- ComplexHeatmap::Heatmap(rep_type_matrix,col=c('white','red'),name = 'Count',cell_fun =  function(j, i, x, y, width, height, fill) {
  if(rep_type_matrix[i, j]>0){
    grid.text(sprintf("%.3s", rep_type_matrix[i, j]), x, y, gp = gpar(fontsize = 11))
  }
},show_heatmap_legend = F,cluster_rows = F,column_title = "Replicon type",height = unit(8, "cm"),show_column_dend = T,width =ncol(rep_type_matrix)*unit(0.6, "cm"), column_names_max_height = unit(6, "cm"))

H

maxchar <- colnames(rep_type_matrix) %>% sapply(nchar) %>% max
```

# I. Relaxase type
```{r}
relaxase_type_matrix <- mobtyper  %>% subset(primary_cluster_id %in% ESCrE_plasmids) %>% select(genomic_id,primary_cluster_id,relaxase_types)%>%
  separate_rows(relaxase_types,sep=",") %>%
  group_by(primary_cluster_id,relaxase_types) %>%
  summarise(n=n(),.groups='drop')  %>% as.data.frame %>% mutate(relaxase_types = recode(relaxase_types,"-" = 'Absent')) %>%
  pivot_wider(names_from = relaxase_types,values_from = n,values_fill = 0) %>%
  as.data.frame() %>% `rownames<-`(.$primary_cluster_id) %>% select(-primary_cluster_id) 

colnames(relaxase_type_matrix) <- sapply(colnames(relaxase_type_matrix),FUN=function(x){
  charl <- nchar(x)
  padding <- maxchar - charl +10
  paste0(paste0(rep(" ",padding),collapse=""),x,collapse = "")
})

I <- ComplexHeatmap::Heatmap(relaxase_type_matrix,col=c('white','red'),name = 'Count',cell_fun =  function(j, i, x, y, width, height, fill) {
  if(relaxase_type_matrix[i, j]>0){
    grid.text(sprintf("%.3s", relaxase_type_matrix[i, j]), x, y, gp = gpar(fontsize = 11))
  }
},show_heatmap_legend = F,cluster_rows = F,column_title = "Relaxase type",height = unit(8, "cm"),show_column_dend = T, width =ncol(relaxase_type_matrix)*unit(0.6, "cm"), column_names_max_height = unit(5, "cm"))

I
```

# J. MPF Type
```{r} 
mpf_type_matrix <- mobtyper  %>% subset(primary_cluster_id %in% ESCrE_plasmids)  %>% select(genomic_id,primary_cluster_id,mpf_type)%>%
  separate_rows(mpf_type,sep=",") %>%
  group_by(primary_cluster_id,mpf_type) %>%
  summarise(n=n(),.groups='drop') %>% as.data.frame %>% mutate(mpf_type = recode(mpf_type,"-" = 'Absent'))  %>%
  pivot_wider(names_from = mpf_type,values_from = n,values_fill = 0) %>%
  as.data.frame() %>% `rownames<-`(.$primary_cluster_id) %>% select(-primary_cluster_id) 

colnames(mpf_type_matrix) <- sapply(colnames(mpf_type_matrix),FUN=function(x){
  charl <- nchar(x)
  padding <- maxchar - charl +10
  paste0(paste0(rep(" ",padding),collapse=""),x,collapse = "")
})

J <- ComplexHeatmap::Heatmap(mpf_type_matrix,col=c('white','red'),name = 'Count',cell_fun =  function(j, i, x, y, width, height, fill) {
  if(mpf_type_matrix[i, j]>0){
    grid.text(sprintf("%.3s", mpf_type_matrix[i, j]), x, y, gp = gpar(fontsize = 11))
  }
},show_heatmap_legend = F,cluster_rows = F,column_title = "MPF type",height = unit(8, "cm"),show_column_dend = T,width =ncol(mpf_type_matrix)*unit(0.6, "cm"), column_names_max_height = unit(5, "cm"))

J
```

# K. oriT type
```{r} 
orit_type_matrix <- mobtyper %>% subset(primary_cluster_id %in% ESCrE_plasmids) %>% select(genomic_id,primary_cluster_id,orit_types)%>%
  separate_rows(orit_types,sep=",") %>%
  group_by(primary_cluster_id,orit_types) %>%
  summarise(n=n(),.groups='drop') %>% as.data.frame %>% mutate(orit_types = recode(orit_types,"-" = 'Absent')) %>%
  pivot_wider(names_from = orit_types,values_from = n,values_fill = 0) %>%
  as.data.frame() %>% `rownames<-`(.$primary_cluster_id) %>% select(-primary_cluster_id) 

colnames(orit_type_matrix) <- sapply(colnames(orit_type_matrix),FUN=function(x){
  charl <- nchar(x)
 padding <- maxchar - charl+10
  paste0(paste0(rep(" ",padding),collapse=""),x,collapse = "")
})

K <- ComplexHeatmap::Heatmap(orit_type_matrix,col=c('white','red'),name = 'Count',cell_fun =  function(j, i, x, y, width, height, fill) {
  if(orit_type_matrix[i, j]>0){
    grid.text(sprintf("%.3s", orit_type_matrix[i, j]), x, y, gp = gpar(fontsize = 11))
  }
},show_heatmap_legend = F,cluster_rows = F,column_title = "oriT type",height = unit(8, "cm"),width = ncol(orit_type_matrix)*unit(0.6, "cm"),show_column_dend = T, column_names_max_height = unit(5, "cm"))

K 
```

# Grouped figure
```{r,fig.height=16,fig.width=12.8}
fig_histograms <- cowplot::plot_grid(A,B,ncol=2,labels = c("A","B"),rel_widths = c(1,1))
fig_histograms2 <- cowplot::plot_grid(C +theme(legend.position='none'),D+ theme(legend.position='none'),E + theme(legend.position='none'),ncol=3,labels = c("C","D","E"))

fig_facet_histograms <-  cowplot::plot_grid(f,G,ncol=2,rel_widths=c(1,1),labels = c("F","G")) 
  
I_mat <-  grid.grabExpr(draw(H))
J_mat <-  grid.grabExpr(draw(I))
K_mat <-  grid.grabExpr(draw(J))
L_mat <-  grid.grabExpr(draw(K))

heatmaps_cow <- cowplot::plot_grid(I_mat,J_mat,K_mat,L_mat,nrow=1,labels = c('H','I',"J",'K'),rel_widths = c(1,0.4,0.4,0.4),align='hv')

figure <- cowplot::plot_grid(fig_histograms,fig_histograms2,fig_facet_histograms,heatmaps_cow,ncol=1,rel_heights=c(0.66,0.5,0.66,1))

figure
```

```{r}
ggsave("./figures/s_figure_2_mobtyper_plasmid_overview.png",plot=figure, units='in',height=16,width=12.8,dpi=900,bg='white')
```
