# profile/config.yaml

# General snakemake parameters
use-conda: true
use-singularity: true
use-envmodules: true
printshellcmds: true
latency-wait: 100
nolock: true
conda-frontend: mamba
jobs: 500

# Slurm parameters
slurm: true
max-jobs-per-second: 5
max-status-checks-per-second: 0.5

# Default slurm resources
default-resources:
  slurm_account: esnitkin1
  slurm_partition: standard
  runtime: 120
  mem_mb: 5000
  slurm_extra: "'--output=slurm_out/slurm-%j.out'"

local-cores: 1
rerun-incomplete: true
keep-going: true
retries: 2