---
title: "Curate raw MERLIN metadata"
output: html_document
date: "`r Sys.Date()`"
---

Note:
1. Received new data on 03/20/25
2. Received update with plate data on 3/27/25
2. Received update with final plate data on 4/01/25

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_merlin/Analysis/Household_transmission/')
```

# Environment
```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load Data 
```{r} 
metadata <- readxl::read_xlsx('../data/Positive_ND_Isolates_Sent_to_MI_comb_sensi_etest_20250402.xlsx',trim_ws = T)  
metadata <- as.data.frame(metadata) 
```

# Clean Datasets 
## Isolate variable
```{r}
# Remove whitespace
metadata$isolate_id_recode <- recode(metadata$isolate_id,
                                    'Stool 1A C1 (00792)' = 'Stool 1A C1',
                                    'Bath 1 C2 (pink)' = 'Bath 1 C2',
                                    'Stool 1A C1 (00794)' = 'Stool 1A C1',
                                    'Stool 1A C1 (01238)' = 'Stool 1A C1',
                                    'Kitchen C1 (01240)' = 'Kitchen C1') 

# Harmonize isolate ID information
## Petnape -> Pet Nape
metadata$isolate_id_recode <- gsub(pattern = "Petnape",replacement = "Pet Nape",metadata$isolate_id_recode)
## Petstool -> Pet Stool
metadata$isolate_id_recode <- gsub(pattern = "Petstool",replacement = "Pet Stool",metadata$isolate_id_recode)
```
## Household id (correct lowercase)
```{r}
# Correct lowercase
metadata$household_number <- recode(metadata$household_number,'49h' = '49H')
```

# Edit specific isolates with coding differences 
```{r}
# 113H_2_Pet Stool 1A C1: Remove C1
metadata$isolate_id_recode <- ifelse(metadata$household_number=="113H" & metadata$visit ==2 & metadata$isolate_id == "Pet Stool 1A C1", "Pet Stool 1A",metadata$isolate_id_recode)

# 113H: Add "C1" to Visit 2 Washing Machine  
metadata$isolate_id_recode <- ifelse(metadata$household_number == "113H" & metadata$visit == 2 & metadata$isolate_id == "Washing Machine","Washing Machine C1", metadata$isolate_id_recode)
 
# 160H: Add "C1" to Visit 1 Bath 1
metadata$isolate_id_recode <- ifelse(metadata$household_number == "160H" & metadata$visit == 1 & metadata$isolate_id == "Bath 1","Bath 1 C1", metadata$isolate_id_recode)

# 182H: Add "C1" to Visit 3 Bath 1 
metadata$isolate_id_recode <- ifelse(metadata$household_number == "182H" & metadata$visit == 3 & metadata$isolate_id == "Bath 1","Bath 1 C1", metadata$isolate_id_recode)

# 197H: Add "C1" to Visit 2 Living Room 
metadata$isolate_id_recode <- ifelse(metadata$household_number == "197H" & metadata$visit == 2 & metadata$isolate_id == "Living Room", "Living Room C1", metadata$isolate_id_recode)

# 151H: Remove "C1" from  Visit 3 Living Room & Washing Room
metadata$isolate_id_recode <- ifelse(metadata$household_number == "151H" & metadata$visit == 3 & metadata$isolate_id == "Living Room C1","Living Room", metadata$isolate_id_recode)

metadata$isolate_id_recode <- ifelse(metadata$household_number == "151H" & metadata$visit == 3 & metadata$isolate_id == "Washing Machine C1","Washing Machine", metadata$isolate_id_recode)
```

# Create useful and parsable tag for isolates
```{r}
# Metadata
metadata$isolate_info <- ifelse(grepl("MER",metadata$household_number)==T,paste0(metadata$isolate_id,"_i"),
                                paste0(metadata$household_number,"_",metadata$visit,"_",metadata$isolate_id_recode))
```

```{r}
saveRDS(metadata,"./MERLIN-prolonged-colonization-ms/data/dataset/isolate_metadata.RDS")
write_csv(metadata,"./MERLIN-prolonged-colonization-ms/data/dataset/isolate_metadata.csv")
```
