---
title: "Data Cleaning Step 7 - Curate final metadataset of specimens from index subjects"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_merlin/')
```

# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse") 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Update - changed from 30 to 25 SNP threshold

```{r}  
# Overall dataset
df <- readRDS("/Users/kgontjes/Desktop/gl_merlin/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/data/dataset/MERLIN_cohort_metadata_final.RDS")
paste0("Number of overall isolates: ",nrow(df))

# QC passing ESCrE genomes
df_qc_passing <-  df %>% subset(qc_pass=="TRUE" & WGS_escre==TRUE)
paste0("Number of overall ESCrE qc-passing isolates: ",nrow(df_qc_passing))

# Index isolates
df_index <- subset(df_qc_passing, index==TRUE)
paste0("Number of index isolates: ",nrow(df_index))
```

# Save
```{r}
saveRDS(df_index,"/Users/kgontjes/Desktop/gl_merlin/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/data/dataset/MERLIN_cohort_index_cases_metadata_final.RDS")
write_csv(df_index,"/Users/kgontjes/Desktop/gl_merlin/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/data/dataset/MERLIN_cohort_index_cases_metadata_final.csv")
``` 
