---
title: "Curate metadata"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_merlin/')
```
 
# Environment

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse",'ggraph','igraph') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

```{r}  
df <- readRDS("./Analysis/Household_transmission/2025-04-08_final_metadata/results/MERLIN_metadata_041525.RDS")  
cluster_30_SNPs <- readRDS("./Analysis/Household_transmission/2025-04-18_SNP_cluster_analysis/results/MERLIN_30_SNP_clusters_041825.RDS")
``` 

# Merge cluster data
```{r}
df <- left_join(df,cluster_30_SNPs)
```

# Edit metadata
```{r}   
df$isolate_no <- df$genomic_id  
df$household <- ifelse(grepl("MER",df$household_number),df$isolate_id,df$household_number) %>% gsub("h","H",.)
df$ST <- ifelse(df$ST =="-","Unknown",df$ST) 
df$Species_ST <- paste0(df$Species," ST ",df$ST) %>% trimws(.,"both")
df$specimen <- ifelse(grepl("MER",df$household_number),"Stool 1A",df$isolate_id)%>% gsub("C1|C2|C3","",.)  %>% trimws(.,"both")  %>% gsub("\\)|pink|00784|01240|01238|00794|\\(","",.) %>% trimws(.,"both")  %>% gsub("Petnape","Pet Nape",.)%>% trimws(.,"both") %>% gsub("Petstool","Pet Stool",.) %>% trimws(.,"both")  

df$specimen_category <- ifelse(df$specimen %in% c("Bath 1","Kitchen","Living Room","Washing Machine"),"Environmnent",
                                           ifelse(df$specimen %in% c("Pet Nape 1A","Pet Nape 2A","Pet Nape 3A","Pet Stool 1A","Pet Stool 2A"),"Pet",
                                                  ifelse(df$specimen %in% c("Stool 1A","Stool 2A","Stool 3A"),"Human","Unk")))

df$individual_id <- paste0(df$household,"_",df$specimen)
df$index <-  grepl('hi',df$location_or_participant) | grepl("MER",df$household_number)
```

# Save
```{r}
saveRDS(df,"/Users/kgontjes/Desktop/gl_merlin/Analysis/Household_transmission/2025-04-18_final_metadata/MERLIN_species_genomic_metadata_041825.RDS")
write_csv(df,"/Users/kgontjes/Desktop/gl_merlin/Analysis/Household_transmission/2025-04-18_final_metadata/MERLIN_species_genomic_metadata_041825.csv")
```

