---
title: "Data Cleaning Step 5- Add QCD data to de-duplicated metadata"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir='~/Desktop/gl_merlin/Analysis/Household_transmission/')
```

# Environment
```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data
```{r}
metadata <- readRDS("./MERLIN-prolonged-colonization-ms/data/dataset/metadata_w_genomic_id_w_duplicate_ESCrE_addressed.RDS") 
qcd <- readRDS("./MERLIN-prolonged-colonization-ms/data/QCD/master_qc_all.RDS")
```

# Merge qcd data
```{r}
merge_qcd_data <- function(WGS_id, QC_flag){
  samples <- str_split(WGS_id,";") %>% unlist
  qcd_subset <- qcd %>% subset(Sample %in% samples & qc_pass==QC_flag)
  if(nrow(qcd_subset)>1){
    qcd_subset <- qcd_subset[match(qcd_subset$Sample,samples),]
    qcd_subset <- qcd_subset  %>%
  summarise(across(everything(), ~ paste(unique(.), collapse = ";")), .groups = "drop")
  }
  return(qcd_subset)
}

qcd_entries <- lapply(metadata$genomic_id,merge_qcd_data,QC_flag='TRUE') %>% do.call(rbind,.) %>% distinct() 

# Failing genomes
failed_genomes <- metadata %>% subset(WGS_qc_pass_runs_num == 0 ) %>% .$Genome_ID
 
qcd_entries_failed <-  lapply(failed_genomes,merge_qcd_data,QC_flag='FALSE') %>% do.call(rbind,.) %>% distinct()
qcd_results <- rbind(qcd_entries,qcd_entries_failed)

metadata <- left_join(metadata, qcd_results)
```
 

# Clean dataframe  
```{r} 
metadata$household <- ifelse(grepl("MER",metadata$household_number_recode), metadata$isolate_id,metadata$household_number_recode) %>% gsub("h","H",.)
metadata$ST <- ifelse(metadata$ST =="-","Unknown",metadata$ST) 
metadata$Species_ST <- paste0(metadata$Species," ST ",metadata$ST) %>% trimws(.,"both")
metadata$specimen <- ifelse(grepl("MER",metadata$household_number_recode),"Stool 1A",metadata$isolate_id)%>% gsub("C1|C2|C3","",.)  %>% trimws(.,"both")  %>% gsub("\\)|pink|00784|01240|01238|00794|00792|\\(","",.) %>% trimws(.,"both")  %>% gsub("Petnape","Pet Nape",.) %>% trimws(.,"both") %>% gsub("Petstool","Pet Stool",.) %>% trimws(.,"both")

metadata$specimen_category <- ifelse(metadata$specimen %in% c("Bath 1","Bath 2","Kitchen","Living Room","Washing Machine"),"Environmnent",
                                           ifelse(metadata$specimen %in% c("Pet Nape 1A","Pet Nape 2A","Pet Nape 3A","Pet Stool 1A","Pet Stool 2A"),"Pet",
                                                  ifelse(metadata$specimen %in% c("Stool 1A","Stool 2A","Stool 3A"),"Human","Unknown")))

metadata$individual_id <- paste0(metadata$household,"_",metadata$specimen)
metadata$index <-  grepl('hi',metadata$location_or_participant) | grepl("MER",metadata$household_number_recode)
metadata$isolate_name <- paste0(metadata$household,"_",metadata$visit,"_",metadata$specimen)
```


```{r}
metadata_clean <- metadata %>% select(-no_correct_platemap,-WGS_qc_pass_runs_num,-WGS_qc_pass_ids_num)
colnames(metadata_clean) <- gsub("\\.|\\.\\.\\.","_",colnames(metadata_clean))

saveRDS(metadata_clean,'./MERLIN-prolonged-colonization-ms/data/dataset/metadata_w_genomic_id_w_duplicate_ESCrE_addressed_w_qcd.RDS')
write.csv(metadata_clean,'./MERLIN-prolonged-colonization-ms/data/dataset/metadata_w_genomic_id_w_duplicate_ESCrE_addressed_w_qcd.csv')
```

