---
title: "Prolonged colonization"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_merlin/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'kableExtra','gontjesr') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data
```{r} 
df_index <- readRDS("./data/dataset/MERLIN_cohort_index_cases_metadata_final.RDS") 
plasmid_data <- readRDS("./data/ESBL_plasmids/MERLIN_index_cohort_beta_lactam_location_data.RDS") %>% subset(genomic_id %in% df_index$genomic_id)

df_index <- left_join(df_index,plasmid_data)
```

# Positive specimens
```{r}
ESCrE_index_positive_households <- df_index %>% subset(visit ==0 & WGS_escre==T) %>% .$household
```

# Species level

## Function
```{r }
get_prolonged_colonization <- function(isolate,metadata,variable){
  isolate_df <- subset(metadata,household==isolate)
  isolate_index <- subset(isolate_df,visit==0) %>% .[[variable]]
  isolate_follow_up <- subset(isolate_df,visit>0)
  isolate_follow_up_same_any <- ifelse(sum(isolate_follow_up[[variable]] == isolate_index)>0,1,0)
  isolate_baseline <- subset(isolate_df,visit==1)
  isolate_baseline_same <- ifelse(sum(isolate_baseline[[variable]] == isolate_index)>0,1,0)
  isolate_one_month <- subset(isolate_df,visit==2)
  isolate_one_month_same <- ifelse(sum(isolate_one_month[[variable]] == isolate_index)>0,1,0)
  isolate_two_month <- subset(isolate_df,visit==3)
  isolate_two_month_same <- ifelse(sum(isolate_two_month[[variable]] == isolate_index)>0,1,0)
  index_at_1_and_or_2 = ifelse(isolate_one_month_same==1 | isolate_two_month_same==1,1,0)
   
  results <- cbind.data.frame(household=isolate,isolate_baseline_same,isolate_one_month_same,isolate_two_month_same,index_at_1_and_or_2)
  colnames(results) <- c("household",paste0(colnames(results)[-1],"_",variable))
  return(results)
}
```

## Data generation
```{r }
any_prolonged <- lapply(ESCrE_index_positive_households,get_prolonged_colonization,df_index,variable='WGS_escre') %>% do.call(rbind,.) 
species_prolonged <- lapply(ESCrE_index_positive_households,get_prolonged_colonization,df_index,variable='Species') %>% do.call(rbind,.)
species_ST_prolonged <- lapply(ESCrE_index_positive_households,get_prolonged_colonization,df_index,variable='Species_ST') %>% do.call(rbind,.)
species_ST_cluster_prolonged <- lapply(ESCrE_index_positive_households,get_prolonged_colonization,df_index,variable='Species_ST_cluster') %>% do.call(rbind,.)

prolonged_df <- left_join(any_prolonged,species_prolonged) %>% left_join(.,species_ST_prolonged) %>% left_join(.,species_ST_cluster_prolonged)
```

# Plasmid level prolonged colonization
## Function
```{r}
# Generic
get_prolonged_colonization_str_split <- function(isolate,metadata,variable,split){
  isolate_df <- subset(metadata,household==isolate)
  isolate_index <- subset(isolate_df,visit==0) %>% .[[variable]] %>% str_split(.,split) %>% unlist %>% subset(is.na(.)==F & .!='')
  
  if(length(isolate_index)==0){
    isolate_follow_up_same_any=0
    isolate_baseline_same=0
    isolate_one_month_same=0
    isolate_two_month_same=0
    index_at_1_and_or_2=0 
    } else{ 
  isolate_one_month <- subset(isolate_df,visit==2) %>% .[[variable]]  %>% str_split(.,split) %>% unlist
  isolate_one_month_same <- ifelse(sum(isolate_one_month %in% isolate_index)>0,1,0)
  isolate_two_month <- subset(isolate_df,visit==3) %>% .[[variable]]  %>% str_split(.,split) %>% unlist 
  isolate_two_month_same <- ifelse(sum(isolate_two_month %in% isolate_index)>0,1,0)
  index_at_1_and_or_2 = ifelse(isolate_one_month_same==1 | isolate_two_month_same==1,1,0)
  }
 
  results <- cbind.data.frame(household=isolate,isolate_one_month_same,isolate_two_month_same,index_at_1_and_or_2)
  colnames(results) <- c("household",paste0(colnames(results)[-1],"_",variable))
  return(results)
}

# Plasmid aware
get_prolonged_colonization_str_split_plasmid_aware <- function(isolate,metadata,chromosome_variable,plasmid_variable,split){
  isolate_df <- subset(metadata,household==isolate)
  isolate_index <- subset(isolate_df,visit==0) 
  isolate_index_plasmid <- isolate_index[[plasmid_variable]] %>% str_split(.,split) %>% unlist %>% subset(is.na(.)==F & .!='')
  isolate_index_chromosome <- isolate_index[[chromosome_variable]] %>% str_split(.,split) %>% unlist %>% subset(is.na(.)==F & .!='')
    
  if(length(c(isolate_index_plasmid,isolate_index_chromosome))==0){
    isolate_follow_up_same_any=0
    isolate_baseline_same=0
    isolate_one_month_same=0
    isolate_two_month_same=0
    index_at_1_and_or_2=0 
    }  else { 
  isolate_one_month_plasmid <- subset(isolate_df,visit==2) %>% .[[plasmid_variable]]  %>% str_split(.,split) %>% unlist
  isolate_one_month_chromosome <-  subset(isolate_df,visit==2) %>% .[[chromosome_variable]]  %>% str_split(.,split) %>% unlist
  isolate_one_month_same <- ifelse(sum(isolate_index_plasmid %in% isolate_one_month_chromosome) | sum(isolate_index_chromosome %in% isolate_one_month_plasmid) >0 | sum(isolate_index_plasmid %in%isolate_one_month_plasmid ) >0,1,0)
  
  isolate_two_month_plasmid <- subset(isolate_df,visit==3) %>% .[[plasmid_variable]]  %>% str_split(.,split) %>% unlist
  isolate_two_month_chromosome <-  subset(isolate_df,visit==3) %>% .[[chromosome_variable]]  %>% str_split(.,split) %>% unlist
  isolate_two_month_same <- ifelse(sum(isolate_index_plasmid %in% isolate_two_month_chromosome) | sum(isolate_index_chromosome %in% isolate_two_month_plasmid) >0 | sum(isolate_index_plasmid %in%isolate_two_month_plasmid ) >0,1,0) 
 
  index_at_1_and_or_2 <- ifelse(isolate_one_month_same==1 | isolate_two_month_same==1,1,0)
    }
  
  results <- cbind.data.frame(household=isolate,isolate_one_month_same,isolate_two_month_same,index_at_1_and_or_2)
  colnames(results) <- c("household",paste0(colnames(results)[-1],"_ESCrE_genes_plasmid_aware"))
  
  return(results)
} 
```

## Data generation
```{r} 
maldi_sharing <- lapply(ESCrE_index_positive_households,get_prolonged_colonization_str_split,df_index,variable='maldi',split=",") %>% do.call(rbind,.)

ESCrE_genes_sharing <- lapply(ESCrE_index_positive_households,get_prolonged_colonization_str_split,df_index,variable='ESCrE_genes',split=";") %>% do.call(rbind,.)
 
ESCrE_plasmid_aware_sharing <- lapply(ESCrE_index_positive_households,get_prolonged_colonization_str_split_plasmid_aware,df_index,chromosome_variable='ESCrE_chromosome_genes',plasmid_variable = "ESCrE_plasmid_genes",split=";") %>% do.call(rbind,.)

prolonged_df <- left_join(prolonged_df,ESCrE_genes_sharing)  %>% left_join(.,ESCrE_plasmid_aware_sharing) %>% left_join(.,maldi_sharing)
```

# Generate merged datapoints
```{r}
prolonged_df$index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes <- ifelse(prolonged_df$index_at_1_and_or_2_Species_ST_cluster==1 | prolonged_df$index_at_1_and_or_2_ESCrE_genes ==1,1,0) 
prolonged_df$index_at_1_and_or_2_Species_ST_cluster_ESCrE_genes_plasmid_aware <- ifelse(prolonged_df$index_at_1_and_or_2_Species_ST_cluster==1 | prolonged_df$index_at_1_and_or_2_ESCrE_genes_plasmid_aware ==1,1,0) 
```

# Save dataset
```{r}
saveRDS(prolonged_df,'./data/prolonged_colonization/MERLIN_prolonged_colonization_index_patients.RDS')
```
