---
title: "Supplementary Table 6: Species-level diagnostic statistics"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_MERLIN/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source library
source("./lib/consistent_themes.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data
```{r}
comparison_of_any_ESCRE_to_WGS_outcomes <- readRDS("./data/diagnostic_statistics/species_level_persistence_diagnostic_statistics/species_level_diagnostic_statistics_public_references.RDS")
```

# Edit column names
```{r}
stable_6 <- comparison_of_any_ESCRE_to_WGS_outcomes %>% select(outcome_rename,tp,fp,tn,fn,sens,spec,ppv,npv,false_persistence_rate,overall_disagreement) 

colnames(stable_6) <- recode(colnames(stable_6),
                            'outcome_rename' = 'Criteria',
                            "tp" = "True positives",
                            "fp" = "False positives",
                            "tn" = "True negatives",
                            "fn" = "False negatives",
                            "sens" = "Sensitivity",
                            'spec' = "Specificity",
                            "ppv" = 'Positive predictive value (PPV)',
                            'npv'='Negative predictive value (NPV)',
                            'false_persistence_rate' = "False persistence rate (1-PPV)",
                            "overall_disagreement" = "Overall disagreement (1-accuracy)")
stable_6 %>% favorite_kable()
```

# Save table as CSV and RDS file
```{r}
saveRDS(stable_6,"./tables/s_table_6_species_level_diagnostic_statistics.RDS")
write_csv(stable_6,"./tables/s_table_6_species_level_diagnostic_statistics.csv")
```