---
title: "Supplementary Table 1: Public reference genome choices for variant calling"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_MERLIN/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse","kableExtra")

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
``` 

# Load reference genome dataset
```{r}
reference_genomes <- readRDS("./data/public_genomes/reference_genome_detection/best_MERLIN_NCBI_reference_genome_choices.RDS") 
```

# Curate metadata
```{r}
reference_genomes$Species <- str_split(reference_genomes$Species_ST," ",simplify=T) %>% .[,1:2] %>% apply(.,1,paste0,collapse=" ")
reference_genomes$analysis_group_clean <- ifelse(reference_genomes$group == 'species',reference_genomes$Species,reference_genomes$group)
```

# Table

```{r}
stable_1 <- reference_genomes %>% select(analysis_group_clean,n_considered_genomes,Ref_name,ST,median_ref_n50,min_ANI,median_ANI,median_aln_fraction_ref)
stable_1$min_ANI <- round(stable_1$min_ANI,2)
stable_1$median_ANI <- round(stable_1$median_ANI,2)
stable_1$median_aln_fraction_ref <- round(stable_1$median_aln_fraction_ref,2) 
colnames(stable_1) <- recode(colnames(stable_1),
                           'analysis_group_clean' = 'Analysis group',
                           'n_considered_genomes' = 'Study genomes',
                           'Ref_name' = 'Reference accession',
                           'ST' = 'Reference ST', 
                           'median_ref_n50' = 'Reference length (bp)',
                           'min_ANI' = 'Minimum ANI',
                           'median_ANI' = 'Median ANI',
                           'median_aln_fraction_ref' = "Median alignment fraction (reference)")

stable_1 %>% favorite_kable()
```

# Save table
```{r}
saveRDS(stable_1,"./tables/s_table_1_variant_calling_reference_genomes.RDS")
write_csv(stable_1,"./tables/s_table_1_variant_calling_reference_genomes.csv")
```
 