---
title: "Supplemental Table 2: Strain and ESBL gene presence stratified by household"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_merlin/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data
```{r cars} 
df_index <- readRDS("./data/dataset/MERLIN_cohort_index_cases_metadata_final.RDS") 
plasmid_data <- readRDS("./data/ESBL_plasmids/MERLIN_index_cohort_beta_lactam_location_data.RDS") %>% subset(genomic_id %in% df_index$genomic_id)

df_index <- left_join(df_index,plasmid_data)
```

# Supplemental Table 2
## Note: Updated to use 25 SNP threshold not 30 due to epidemiological data

```{r}
df_index$household_numeric <- gsub("H","",df_index$household) %>% as.numeric
  
s_table_2 <- df_index %>% arrange(household_numeric,visit,Species_ST_cluster) %>% select(household,visit,Species_ST_cluster,bla_genes,ESCrE_genes,ESCrE_chromosome_genes,ESCrE_plasmid_genes,plasmids,ESCrE_plasmids) %>% mutate(plasmids = gsub(";",", ",plasmids),ESCrE_genes = gsub(";",", ",ESCrE_genes),ESCrE_chromosome_genes = gsub(";",", ",ESCrE_chromosome_genes),ESCrE_plasmid_genes = gsub(";",", ",ESCrE_plasmid_genes),ESCrE_plasmids = gsub(";",", ",ESCrE_plasmids)) %>%  `colnames<-`(c("Household","Visit","Strain","Β-lactamase gene(s)","ESCrE gene(s)",'Chromosomal ESCrE gene(s)','Plasmid-linked ESCrE gene(s)',"Plasmid(s)",'ESCrE plasmid(s)'))
```

```{r}
favorite_kable(s_table_2)
```

```{r}
saveRDS(s_table_2,"./tables/s_table_2_strain_ESCrE_genes_by_index_patient.RDS")
write_csv(s_table_2,"./tables/s_table_2_strain_ESCrE_genes_by_index_patient.csv")
```
