---
title: "curate_genome_download_script"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_merlin/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/')
```

# Environment

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse") 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Master script

```{bash}
cd ./scripts/public_genomes/genome_download/setup/
echo "#!/bin/sh
# Job name
#SBATCH --job-name=download_MERLIN_NCBI_species_genomes
# User info
#SBATCH --mail-user=kgontjes@umich.edu
#SBATCH --mail-type=BEGIN,END,FAILED
#SBATCH --export=ALL
#SBATCH --partition=standard
#SBATCH --account=esnitkin1
#SBATCH --output=/nfs/turbo/umms-esnitkin/Project_MERLIN/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/slurm_out/public_genomes/genome_download/download_NCBI_species_genomes_slurm_out_072026.out
#SBATCH --nodes=1  --ntasks=1 --cpus-per-task=8 --mem=40g --time=1:00:00

# conda activate ncbi_datasets_v_18_33_1
datasets --version
datasets download genome accession --inputfile /nfs/turbo/umms-esnitkin/Project_MERLIN/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/data/public_genomes/species/NCBI_Pathogens_species_isolates_w_spatiotemporal_data_072026.txt --include genome --filename /scratch/esnitkin_root/esnitkin1/kgontjes/Project_MERLIN/Analysis/Household_transmission/MERLIN-prolonged-colonization-ms/data/public_genomes/raw_assemblies/species/NCBI_Pathogens_species_072126.zip 
" > model_download_genomes.sbat
```

# Genome list

```{r}
species <- list.dirs("./data/public_genomes",recursive = T) %>% str_split("\\/",simplify = T) %>% .[,4] %>% subset(.!='') %>% subset(!. %in% c("sliquefaciens","cportucalensis"))

lapply(species,FUN=function(x){
  lines <- readLines("./scripts/public_genomes/genome_download/setup/model_download_genomes.sbat")
  lines <- gsub("species",x,lines)
  writeLines(lines,paste0("./scripts/public_genomes/genome_download/NCBI_Pathogens_",x,"_genome_download_072026.sbat"))
})
```
